#!/usr/bin/env sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

npx lint-staged || 
(
    echo 'Lint Staged failed. Make the required changes listed above, add changes and try to commit again.'
    false; 
)

npm run test ||
(
    echo 'Tests failed. Make the required changes listed above, add changes and try to commit again.'
    false; 
)

echo '✅✅✅✅ Everything looks good! ✅✅✅✅'